ALTER TABLE public."FMS"
ADD COLUMN IF NOT EXISTS document1 TEXT,
ADD COLUMN IF NOT EXISTS document2 TEXT,
ADD COLUMN IF NOT EXISTS additional_documents TEXT,
ADD COLUMN IF NOT EXISTS verification_date TIMESTAMP;
